customhost = "myfirstproject.c04g3nrqseoc.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "saif2406"
customdb = "employe"
custombucket = "firstprojectemployee"
customregion = "ap-south-1"
